wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.1
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1680871504.071416
    t:
      1:
      - 3
      - 55
      2:
      - 3
      - 55
      3:
      - 7
      - 13
      - 23
      - 38
      4: 3.9.16
      5: 0.14.1
      8:
      - 5
    m:
    - 1: epoch/epoch
      6:
      - 3
