wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.1
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1680870927.052756
    t:
      1:
      - 3
      - 55
      2:
      - 3
      - 55
      3:
      - 2
      - 7
      - 13
      - 23
      - 38
      4: 3.9.16
      5: 0.14.1
      8:
      - 5
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_2_loss
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_3_loss
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_4_loss
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_2_obj_acc
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_2_mean_iou
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_2_class_acc
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_2_recall
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_3_obj_acc
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_3_mean_iou
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_3_class_acc
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_3_recall
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_4_obj_acc
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_4_mean_iou
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_4_class_acc
      5: 1
      6:
      - 1
    - 1: epoch/concatenate_4_recall
      5: 1
      6:
      - 1
    - 1: epoch/val_loss
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_2_loss
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_3_loss
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_4_loss
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_2_obj_acc
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_2_mean_iou
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_2_class_acc
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_2_recall
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_3_obj_acc
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_3_mean_iou
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_3_class_acc
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_3_recall
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_4_obj_acc
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_4_mean_iou
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_4_class_acc
      5: 1
      6:
      - 1
    - 1: epoch/val_concatenate_4_recall
      5: 1
      6:
      - 1
    - 1: epoch/lr
      5: 1
      6:
      - 1
    - 1: epoch/learning_rate
      5: 1
      6:
      - 1
