wandb_version: 1

k_anchor:
  desc: null
  value: 18
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.1
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1680876837.389249
    t:
      1:
      - 3
      - 55
      3:
      - 23
      4: 3.9.16
      5: 0.14.1
      8:
      - 5
